### ISSUE TITLE
KG?

### ISSUE THREAD

**Issue by Caesar-s1mple** [ansonb/RECON#10]
I found that there are many duplicated triplets in 'train.txt', 'valid.txt' and 'test.txt' you use.
Does it lead to a leakage?

**Comment by ansonb** [comment]
Hi,

Apologies for the late reply and thanks for your interest in our work.

We uploaded the raw files and there is a chance that there are few duplicates. 
These are likely to cause the data leakage issues and thus we ensured to deduplicate the training and testing data.

Many Thanks
