### ISSUE TITLE
Do you have pre-trained model ready for use?

### ISSUE THREAD

**Issue by marcov131842** [ansonb/RECON#16]
Hi,

I am currently looking into your great work. I download the data and the code but find it will take too much time even with GPUs to train the model. So I am wondering whether a pre-trained model (RECON, or RECON_EAC, etc.) can be provided? Many thanks.

Dennis

**Comment by LOUGBERTI** [comment]
> Hi,
> 
> I am currently looking into your great work. I download the data and the code but find it will take too much time even with GPUs to train the model. So I am wondering whether a pre-trained model (RECON, or RECON_EAC, etc.) can be provided? Many thanks.
> 
> Dennis
Hello, how many results did you reproduce in wikidata

**Comment by kulsingh** [comment]
Hello, 

unfortunately, due to compute issues, we dont have pre-trained models. However, errors have been removed from the code, and we pushed latest changes. Please try to execute latest code. thank you.
