### ISSUE TITLE
Cannot find the category corresponding to P106

### ISSUE THREAD

**Issue by hai-qi** [ansonb/RECON#17]
Hello, your work has benefited me a lot. I want to ask what the category of wikidata is (like P106: Occupation), not just p106. Where can I find the specific category

**Comment by ansonb** [comment]
Hi,

Apologies for the late reply and thanks for your interest in our work.

For our experiments on relation extraction the relation id sufficed. If you are looking for the category as well in addition to the id the wikidata sparql query could be used. this would look something like below for the example of P106:
https://query.wikidata.org/#SELECT%20%20DISTINCT%20%3Flabel%0AWHERE%20%7B%0A%20%20%20%20%20%20%20%20wd%3AP106%20rdfs%3Alabel%20%3Flabel.%0A%20%20%20%20%20%20%20%20FILTER%20%28langMatches%28%20lang%28%3Flabel%29%2C%20%22EN%22%20%29%20%29%0A%20%20%20%20%20%20%7D%20

Hope this helps anyone interested, facing similar issues in the future.

Many Thanks
