### ISSUE TITLE
NYT train split size

### ISSUE THREAD

**Issue by AndreiCComan** [ansonb/RECON#18]
Hi,

thank you for your valuable work!

I was wondering how come the `dataset_triples_train.json` file contains 570,084 examples, while in the paper it is indicated 455,771?

Best,
Andrei

**Comment by ansonb** [comment]
Hi,

Apologies for the late reply and thanks for your interest in our work.

The number stated in the paper is the number of sentences while the entities/triples are extracted from the sentence, which may contain more than one triple. So the number of triples could be different.

Hope this helps anyone interested, with similar queries in the future.

Many Thanks
