### ISSUE TITLE
File missing -vocab.json and  char_v.json 

### ISSUE THREAD

**Issue by SoTWhat** [ansonb/RECON#3]
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    word_vocab, char_vocab, word_embed_matrix = build_vocab(args, entities_context_data, save_vocab, embedding_file)
  File "main.py", line 187, in build_vocab
    with open(save_path[0],'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './vocab.json'

please upload the missing file
thanks

**Comment by amiroft** [comment]
Same for me:(

**Comment by ansonb** [comment]
Hi,
Thanks for trying the code and pointing the issue.

The file is actually created during training and if already created then we set the flag USE_VOCAB to true for reuse. It seems this was set to true by default. I've made it false and pushed the changes.
Thanks
