### ISSUE TITLE
P-R Curve

### ISSUE THREAD

**Issue by RedVelvetCake21** [ansonb/RECON#5]
Could you provide the macro_pr and micro_pr result on Wikidata Dataset please?

**Comment by ansonb** [comment]
Hi,

Please find the results as below the results. It's also in the paper. Are you asking something else?

![wikidata_macro](https://user-images.githubusercontent.com/6957575/150676569-1061d572-6752-44d4-929b-9db25efd3ac2.png)
![wikidata_micro](https://user-images.githubusercontent.com/6957575/150676571-374de08e-b1ab-4fc1-87bb-60c705d72b4d.png)
