### ISSUE TITLE
ImportError: cannot import name  'logger'  from  'joblib'

### ISSUE THREAD

**Issue by ZMD177** [ansonb/RECON#6]
Is it a problem with the scikit-learn version?
If it is which version should be downloaded

**Comment by ansonb** [comment]
Hi,

I'm not able to reproduce this error. Not sure why you are facing this...maybe some more info could help. 
If the error is due to something like "from joblib import logger" which you have used, joblib version 1.0.1 may work.

I may upload the requirements.txt file for all dependencies.

Thanks
