### ISSUE TITLE
Hello, i have  a question about RECON

### ISSUE THREAD

**Issue by LOUGBERTI** [ansonb/RECON#7]
I downloaded your files, but some files are not displayed. Can you give me some advice
![Uploading 运行截图.png…]()

**Comment by ansonb** [comment]
Hi,
Thanks for your interest in our work.

For some reason I'm not able to see the image you posted. Could you please reupload or maybe describe what exactly is the issue? Which files are not being displayed etc.?

Thanks

**Comment by LOUGBERTI** [comment]
Hello,&nbsp;
Thank you very much for your reply.
I've been studying your paper recently. I think it's a very excellent paper. After reading your paper, I learned a lot of new things.
I have downloaded the dataset and then run it. I found such an error.











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anson ***@***.***&gt;; 
发送时间: 2022年3月31日(星期四) 上午10:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ansonb/RECON] Hello, i have  a question about RECON (Issue #7)





 
Hi,
 Thanks for your interest in our work.
 
For some reason I'm not able to see the image you posted. Could you please reupload or maybe describe what exactly is the issue? Which files are not being displayed etc.?
 
Thanks

**Comment by kulsingh** [comment]
thank you. Please see the latest changes pushed in the codebase. It shall remove the previous errors.
